version: "3"

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
    networks:
      - iot
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    ports:
      - "8086:8086"
    networks:
      - iot

  telegraf:
    image: telegraf:1.25
    container_name: telegraf
    restart: always
    user: telegraf:996
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - iot
  
  grafana:
    image: grafana/grafana-oss:8.2.6
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - iot

networks:
  iot:
